// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLP0MY6H5rLYZfPA6DkejQ2nBwce_LjVs',
    appId: '1:547981406167:web:df4e394501388009032592',
    messagingSenderId: '547981406167',
    projectId: 'barbershop-ee46a',
    authDomain: 'barbershop-ee46a.firebaseapp.com',
    storageBucket: 'barbershop-ee46a.appspot.com',
    measurementId: 'G-4LGC9ZM3DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAeGXkDiLlYrDUlk2W93h9N-xUiaVIths',
    appId: '1:547981406167:android:fb5a7056b8cb6eca032592',
    messagingSenderId: '547981406167',
    projectId: 'barbershop-ee46a',
    storageBucket: 'barbershop-ee46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37hv_WR0hqBs_Su6WueuCiuv-am1Et0A',
    appId: '1:547981406167:ios:4551f647301d3b1e032592',
    messagingSenderId: '547981406167',
    projectId: 'barbershop-ee46a',
    storageBucket: 'barbershop-ee46a.appspot.com',
    iosBundleId: 'com.example.doanBarberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37hv_WR0hqBs_Su6WueuCiuv-am1Et0A',
    appId: '1:547981406167:ios:6f619ca8b978c042032592',
    messagingSenderId: '547981406167',
    projectId: 'barbershop-ee46a',
    storageBucket: 'barbershop-ee46a.appspot.com',
    iosBundleId: 'com.example.doanBarberapp.RunnerTests',
  );
}
